### ISSUE TITLE
Profiles from csv files should specify grid in configuration data

### ISSUE THREAD

**Issue by mattldawson** [NCAR/tuv-x#137] opened 2022-08-19 19:44 UTC
There should be a grid specified in the configuration data for profiles, instead of assuming the profile is on the ``height`` grid:

```
{
  "type": "from csv file",
  "units": "foos",
  "file path": "path/to/file.csv",
  "grid": {
    "name": "bar",
    "units": "bazes"
  }
}
```

**Comment by K20shores** [comment] 2022-08-22 13:57
@mattldawson Is this a duplicate of #123>

**Comment by mattldawson** [comment] 2022-08-22 15:31
> @mattldawson Is this a duplicate of #123?

oh yeah, wow that wasn't even that long ago and I completely forgot I opened that. I'll close that one, since this is already linked to the PR

**Closed** 2022-08-22 19:24 UTC
Labels: enhancement, points: 1
